//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRCMuteSync.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VRCMuteSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Not Set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_NotSet {
            get {
                return ResourceManager.GetString("Msg_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a valid port number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Msg_PortError {
            get {
                return ResourceManager.GetString("Msg_PortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * Press Esc to clear / Special keys like F13-F24 recommended に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Hint {
            get {
                return ResourceManager.GetString("Win_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Discord Mute Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Hotkey {
            get {
                return ResourceManager.GetString("Win_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click here and press a key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Placeholder {
            get {
                return ResourceManager.GetString("Win_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OSC Receive Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Port {
            get {
                return ResourceManager.GetString("Win_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save and Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Save {
            get {
                return ResourceManager.GetString("Win_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run this app automatically when Windows starts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Startup {
            get {
                return ResourceManager.GetString("Win_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VRCMuteSync Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Win_Title {
            get {
                return ResourceManager.GetString("Win_Title", resourceCulture);
            }
        }
    }
}
